config/routes.rb
Rails.application.routes.draw do

  get 'signup_form/signup_form'

  devise_for :users

  resources :users, only: [:show]
  get '/professional_dashboard', to: 'users#professional_dashboard', as: 'p_dashboard'
  root to: 'pages#landing'
  get 'teacher_info', to: 'pages#teacher_info', as: :teacher_info
  get 'professional_info', to: 'pages#professional_info', as: :professional_info
  get '/tagged', to: "professionals#tagged", as: :tagged

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :professionals, except: :destroy do # only: [:index, :show, :new, :create, :edit, :update]
    resources :lectures, only: [:new, :create, :index] do
      resources :comments, only: [:new, :create]
    end
  end

  resources :teachers, only: [:new, :create, :edit, :update] do
    resources :lectures, only: [:index] do
      resources :comments, only: [:new, :create]
    end
    resources :class_rooms, only: [:new, :create]
  end

  resources :lectures, only: [:show, :edit, :update] do
    resources :comments, only: [:new, :create]
  end
  resources :videotokens, only: [:create]
end

app/models/professional.rb
class Professional < ApplicationRecord
  has_many :lectures
  belongs_to :user
  validates :company, presence: true
  validates :title, presence: true
  validates :user_id, presence: true
  acts_as_taggable_on :expertises
end

app/controllers/professionals_controller.rb
class ProfessionalsController < ApplicationController
  before_action :set_professional, only: [:show, :edit, :update]

  def index
    @professionals = Professional.all
    @professionals = Professional.tagged_with(params["query"]) if params["query"].present?
    @professionals = Professional.tagged_with(params["tag"]) if params["tag"].present?
    @lecture = Lecture.new
  end


  def show
  end

  def new
    @professional = Professional.new
  end

  def create
    @professional = Professional.new(professional_params)
    @professional.user = current_user
    if @professional.save
      redirect_to p_dashboard_path(current_user)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @professional.update(professional_params)
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def tagged
    if params[:tag].present?
      @professionals = Professional.tagged_with(params[:expertise_list])
    else
      @professionals = Professional.all
    end
  end

  private

  def set_professional
    @professional = Professional.find(params[:id])
  end

  def professional_params
    params.require(:professional).permit(:company, :title, :description, :city, :linkedin_url, :expertise_list)
  end
end

app/views/professionals/_form.html.erb
  <%= simple_form_for @professional do |f| %>
    <%= f.input :company %>
    <%= f.input :title %>
    <%= f.submit "Create profile", class: "btn btn-primary ml-2" %>
  <% end %>

app/views/professionals/edit.html.erb
<h1>Professionals#edit</h1>
<p>Find me in app/views/professionals/edit.html.erb</p>

app/views/professionals/index.html.erb
<!-- Find professionals header -->
<div class="banner-short" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1528901166007-3784c7dd3653?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80)">
  <h2>Find Professionals</h2>
</div>
<!-- script for picking category -->
<!-- <div class="container"> -->
<!-- SEARCH -->
<!--   <%#= simple_form_for :search, url: professionals_path, method: "GET", html: { class: 'form-inline' } do |f| %>
    <%#= f.input :name, input_html: {value: ""} %>
    <%#= f.submit "Search", class: "btn btn-primary" %>
  <%# end %> -->
<!-- script for picking category -->
<!--   <div class="dropdown">
    <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Dropdown button
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <%# @professionals.each do |r| %>
        <div class="drop-down-item">
            <%# array = [] %>
            <p>
              <%# r.expertise_list.each do |tag| %>
                <%# array.include?(tag) ? skip : array << tag%>
                <%#= link_to tag, tagged_path(tag: tag) %>
              <%# end %>
            </p>
        </div>
      <%# end %>
    </div>
  </div> -->
<!-- script for picking category -->
<!--   <script>
    $(document).ready(function(){
      $("#myInput").on("keyup", function() {
        var value = $(this).val().toLowerCase();
        $(".dropdown-menu li").filter(function() {
          $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
        });
      });
    });
  </script> -->
<!-- script for picking category -->
<!--   <script>
    $(document).ready(function() {
    $('.js-example-basic-single').select2();
    });
  </script> -->
<!-- </div> -->
<div class="container flex-column align-items-center">
  <div style="width: 90%;" class="mb-4">
    <%= form_tag professionals_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Search on expertise"
      %>
    <% end %>
  </div>
  <% if params[:tag].present? %>
    <h4 class="mb-4 text-white px-2 py-1 rounded bg-info d-inline-block"><%= "##{params[:tag]}" %></h4>
  <% end %>
  <!-- Display professionals -->
  <% @professionals.each do |pro| %>
    <div class="card mb-5" style="width: 90%; border-radius: 12px; box-shadow: 0 0px 40px 0 rgba(0, 0, 0, 0.1); padding: 50px;">
      <div class="row no-gutters">
        <div class="col-md-3">
          <div class="card-body">
            <img src=<%= pro.user.profile_picture_url %> class="avatar-large card-img rounded-circle" alt="profile picture">
          </div>
        </div>
        <div class="col-md-9">
          <div class="card-body">
            <h3 class="card-title" style="color: #7098FF"><%= pro.user.first_name %> <%= pro.user.last_name %></h3>
            <h5 class="card-text"><i class="fas fa-building mr-3"></i><%= pro.company %></h5>
            <p><%= pro.title %></p>
            <div class="d-flex justify-content-between align-items-end">
              <div class="d-flex">
                <p class="card-text"><i class="fas fa-tag"></i>
                  <% pro.expertise_list.each do |e| %>
                    <form action="" method="get">
                      <small class="text-white px-2 mr-1 py-1" style="border-radius: 15px; background-color:#58C2F1;"><%= e %></small>
                    </form>
                  <% end %>
                </p>
              </div>
              <%= link_to 'Send a request', new_professional_lecture_path(pro), class: 'btn btn-primary' %>
              <!--               <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Send request</button> -->
            </div>
          </div>
          <!-- Modal -->
          <div class="modal fade" id="myModal" role="dialog">
            <div class="modal-dialog">
              <!-- Modal content-->
              <div class="modal-content">
                <div class="modal-header">
                  <h4 class="modal-title">Send a request</h4>
                  <%= simple_form_for [pro, @lecture] do |f| %>
                    <div>
                      <%= f.input :name, label: :Topic, required: true %>
                      <%= f.input :start_time, as: :string, required: false, input_html: {class: "datepicker"} %>
                      <%= f.input :end_time, as: :string, required: false, input_html: {class: "datepicker"} %>
                      <%= f.input :message, as: :text %>
                      <%= f.association :class_room, collection: current_user.class_rooms %>
                      <%= f.submit :Request, class: "btn btn-primary" %>
                    </div>
                  <% end %>
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div>
                  <!-- date picker -->
                  <div class="container">
                    <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
                      <!--                       <%#= simple_form_for [@professional, @lecture], new_professional_lecture_path(pro) do |f| %>
                        <%#= f.input :starts_at, as: :string, required: false, input_html: {class: "datepicker"} %>
                        <%#= f.input :ends_at, as: :string, required: false, input_html: {class: "datepicker"} %>
                        <%#= f.input :text %>
                        <%#= f.submit :Request, class: "btn btn-primary" %>
                      <%# end %> -->
                      <%#= render 'lectures/form', lecture: @lecture %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/professionals/new.html.erb
<h1>Professionals#new</h1>
<p>Find me in app/views/professionals/new.html.erb</p>
<div class="container">
  <%= simple_form_for [@user.professional] do |f| %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :profile_picture_url %>
    <%= f.label :background_picture_url %>
    <%= f.input :company %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :city %>
    <%= f.input :linkedin_url %>
    <%= f.submit "Create profile", class: "btn btn-primary ml-2" %>
  <% end %>
</div>

app/views/professionals/show.html.erb
<h1>Professionals#show</h1>
<p>Find me in app/views/professionals/show.html.erb</p>