config/routes.rb
Rails.application.routes.draw do

  get 'signup_form/signup_form'

  devise_for :users

  resources :users, only: [:show]
  get '/professional_dashboard', to: 'users#professional_dashboard', as: 'p_dashboard'
  root to: 'pages#landing'
  get 'teacher_info', to: 'pages#teacher_info', as: :teacher_info
  get 'professional_info', to: 'pages#professional_info', as: :professional_info
  get '/tagged', to: "professionals#tagged", as: :tagged

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :professionals, except: :destroy do # only: [:index, :show, :new, :create, :edit, :update]
    resources :lectures, only: [:new, :create, :index] do
      resources :comments, only: [:new, :create]
    end
  end

  resources :teachers, only: [:new, :create, :edit, :update] do
    resources :lectures, only: [:index] do
      resources :comments, only: [:new, :create]
    end
    resources :class_rooms, only: [:new, :create]
  end

  resources :lectures, only: [:show, :edit, :update] do
    resources :comments, only: [:new, :create]
  end
  resources :videotokens, only: [:create]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :teachers, dependent: :destroy
  has_many :professionals, dependent: :destroy
  has_many :class_rooms, through: :teachers
  has_many :lectures, through: :class_rooms
  has_many :lectures, through: :professionals
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @teacher = current_user.teachers.first
    @professional = current_user.professionals.first
    @class_room = ClassRoom.new(teacher: @teacher)
    @lectures = current_user.teachers.first.lectures.order(:start_time)
  end

  def professional_dashboard
    @user = current_user
    @professional = current_user.professionals.first
    @lectures = current_user.lectures
  end
end

app/views/users/professional_dashboard.html.erb
<div class="banner-profile">
  <div class="container d-flex align-items-center">
    <img src=<%= current_user.profile_picture_url %> alt="Avatar" class="avatar-large mr-5">
    <div class="text-white">
      <h2><%= @user.first_name %> <%= @user.last_name %></h2>
      <h3><%= @professional.title %></h3>
      <p><%= @professional.company %></p>
    </div>
  </div>
</div>
<div class="container">
  <!-- TAB BARS -->
  <ul class="nav nav-pills mb-5">
    <li class="nav-item">
      <a class="nav-link active" data-toggle="tab" href="#profile">My Profile</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#requests">Requests</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#lectures">Upcoming lectures</a>
    </li>
  </ul>
  <div class="tab-content">
    <!-- TAB 1 CLASSROOMS -->
    <div id="profile" class="tab-pane active show">
      <!-- <h5>You don’t have any class rooms yet. Create your first one.</h5>
    </div>


    <!-- TAB 1 add profile to card -->
      <div class="card mb-3" style="width: 100%; border-radius: 12px; box-shadow: 0 0px 40px 0 rgba(0, 0, 0, 0.1); padding: 50px;">
        <div class="grid-container">
          <div class="CompanyValue">
            <h5 class="mb-4"><%= @professional.company %></h5>
          </div>
          <div class="CompanyLabel">
            <h5><i class="fas fa-building" style="color:#7098FF"></i> Company</h5>
          </div>
          <div class="FullName">
            <h2 class="mb-5" style="color: #7098FF">About me</h2>
          </div>
          <div class="JobTitleLabel">
            <h5 class="mb-4"><i class="fas fa-user-tie" style="color:#7098FF"></i> Job Title</h5>
          </div>
          <div class="JobTitleValue">
            <h5 class="mb-4"><%= @professional.title %></h5>
          </div>
          <div class="CityLabel">
            <h5 class="mb-4"><i class="fas fa-city" style="color:#7098FF"></i> City</h5>
          </div>
          <div class="CityValue">
            <h5 class="mb-4"><%= @professional.city %></h5>
          </div>
          <div class="EmailLabel">
            <h5 class="mb-4"><i class="fas fa-envelope" style="color:#7098FF"></i> Email</h5>
          </div>
          <div class="EmailValue">
            <h5 class="mb-4"><%= @user.email %></h5>
          </div>
          <div class="LinkedinLabel">
            <h5 class="mb-4"><i class="fab fa-linkedin" style="color:#7098FF"></i> LinkedIn</h5>
          </div>
          <div class="LinkedinValue">
            <h5 class="mb-4" style="color:#7098FF"><%= @professional.linkedin_url %></h5>
          </div>
          <div class="DescriptionLabel">
            <h5 class="mb-4"><i class="fas fa-smile" style="color:#7098FF"></i> Expertise</h5>
          </div>
          <div class="DescriptionValue">
            <h5 class="mb-4">
                <% @professional.expertise_list.each do |e| %>
                  <small class="text-white px-2 py-1" style="border-radius: 15px; background-color:#58C2F1;"><%= e %></small>
                <% end %>
            </h5>
          </div>
          <div class="EditProfileButton"><a class="mt-4 btn btn-primary py-1" href="/lectures/5">Edit Profile</a></div>
        </div>
      </div>
    </div>
    <!-- TAB 2 REQUESTS -->
    <div id="requests" class="tab-pane fade">
      <div class="container">
        <!-- REQUESTS CARD -->
        <% @lectures.each do |l| %>
          <% if !l.confirmed? %>
            <div class="card mb-5 p-5" style="width: 100%; border-radius: 12px; box-shadow: 0 0px 40px 0 rgba(0, 0, 0, 0.1);">
              <div class="row no-gutters">
                <div class="col-md-3">
                  <div class="card-body">
                    <% cr = l.class_room %>
                    <% t = cr.teacher %>
                    <img src=<%= t.user.profile_picture_url %> class="avatar-large card-img rounded-circle" alt="profile picture">
                  </div>
                </div>
                <div class="col-md-9">
                  <h3 class="ml-4" style="color: #7098FF"><i class="fas fa-school"></i> <%= t.school %> | <%= l.class_room.name %></h3>
                  <h5 class="ml-4 mt-4">We want to learn about:</h5>
                  <h4 class="ml-4 m-0 pb-0" style="color: #7098FF">
                    <%= l.name %></h4>
                  <div class="d-flex justify-content-between">
                    <div>
                      <h5 class="ml-4 mt-4 pb-0">Date:</h5>
                      <h6 class="ml-4"><%= l.start_time.strftime('%A, %B %e') %></h6>
                      <h6 class="ml-4"><%= l.start_time.strftime('%l:%M %p') %> - <%= l.end_time.strftime('%l:%M %p') %></h6>
                      <div class="ml-4 mt-4 message-teacher">
                        <h5>Message from the Teacher:</h5>
                        <h6><%= l.message %></h6>
                        <h6 class="mt-4">My students' interests:</h6>
                        <div class="d-flex justify-content-between align-items-end">
                          <p class="">
                            <% cr.interest_list.each do |e| %>
                              <small class="text-white px-2 py-1" style="border-radius: 15px; background-color:#58C2F1;"><%= e %></small>
                            <% end %>
                          </p>
                        </div>
                        <h6 class="mb-1"><i class="fas fa-graduation-cap mr-2"></i> <%= t.user.first_name %> <%= t.user.last_name %></h6>
                      </div>
                      <div class="ml-4">
                        <%= simple_form_for(l) do |f| %>
                          <%= f.submit :Confirm, class: 'btn btn-primary p-2 mt-5'  %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <!-- TAB 3 LECTURES -->
    <div id="lectures" class="tab-pane fade">
      <!--       <h3>Your upcoming lectures</h3>
      <p>You don't have any upcoming lectures yet.</p> -->
      <!-- REQUESTS CARD -->
      <% @lectures.each do |l| %>
        <% if l.confirmed? %>
          <div class="card mb-3 p-5" style="width: 100%; border-radius: 12px; box-shadow: 0 0px 40px 0 rgba(0, 0, 0, 0.1);">
            <div class="row no-gutters">
              <div class="col-md-3">
                <div class="card-body">
                  <% cr = l.class_room %>
                  <% t = cr.teacher %>
                  <img src=<%= cr.picture_url %> class="avatar-large card-img rounded-circle" alt="profile picture">
                </div>
              </div>
              <div class="col-md-9">
                <h3 class="ml-4" style="color: #7098FF"><i class="fas fa-school"></i> <%= t.school %> | <%= l.class_room.name %></h3>
                <h5 class="ml-4 mt-4">You will teach about:</h5>
                <h4 class="ml-4" style="color: #7098FF">
                  <%= l.name %></h4>
                <h5 class="ml-4 mt-4">Date</h5>
                <h6 class="ml-4"><%= l.start_time.strftime('%A, %B %e') %></h6>
                <h6 class="ml-4"><%= l.start_time.strftime('%l:%M %p') %> - <%= l.end_time.strftime('%l:%M %p') %></h6>
                <h5 class="ml-4 mt-4">Class interests:</h5>
                <div class="ml-4 d-flex justify-content-between align-items-end">
                  <p>
                    <% cr.interest_list.each do |e| %>
                      <small class="text-white px-2 py-1" style="border-radius: 15px; background-color:#58C2F1;"><%= e %></small>
                    <% end %>
                  </p>
                </div>
                <div>
                  <a><%= link_to 'Go to lecture', lecture_path(l), :class=>"btn btn-primary ml-4 mt-4" %></a>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="banner-profile">
  <div class="container d-flex align-items-center">
    <img src=<%= current_user.profile_picture_url %> alt="Avatar" class="avatar-large mr-5">
    <div class="text-white">
      <h2><%= @user.first_name %> <%= @user.last_name %></h2>
      <h3><%= @teacher.title %></h3>
      <p><%= @user.email %></p>
      <p><%= @teacher.school %></p>
    </div>
  </div>
</div>
<div class="container">
  <!-- TAB BARS -->
  <ul class="nav nav-pills mb-5">
    <li class="nav-item">
      <a class="nav-link active" data-toggle="tab" href="#classrooms">Classrooms</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#lectures">Lectures</a>
    </li>
  </ul>
  <!--   <ul class="nav nav-tabs mb-3">
    <li class="li-tags" class="active"><a data-toggle="tab" href="#classrooms">Classrooms</a></li>
    <li class="li-tags"><a data-toggle="tab" href="#lectures">Lectures</a></li>
  </ul> -->
  <div class="tab-content">
    <!-- TAB 1 CLASSROOMS -->
    <div id="classrooms" class="tab-pane fade in active show">
      <!-- create new classroom link -->
      <div class="row"><button type="button" class="btn btn-success mb-5 w-30 py-2 ml-3 float-right" data-toggle="modal" data-target="#myModal">Create a new classroom</button>
      </div>
      <!-- <h5>You don’t have any class rooms yet. Create your first one.</h5> -->
      <!-- <div class="container"> -->
      <!-- CLASS CARD -->
      <div class="row">
        <% @user.class_rooms.reverse_each do |cr| %>
          <div class="col-12 col-md-6">
            <div class="card mb-5" style="border-radius: 12px; box-shadow: 0 0px 40px 0 rgba(0, 0, 0, 0.1);">
              <img src=<%= cr.picture_url %> class="card-img-top" alt="..." style="border-radius: 12px 12px 0 0;">
              <div class="card-body pb-2">
                <h3 class="card-title pb-2"><%= cr.name %></h3>
                <h4>Interests</h4>
                <% cr.interest_list.each do |i| %>
                  <small class="text-white px-2 py-1" style="border-radius: 15px; background-color:#58C2F1;"><%= i %></small>
                <% end %>
              </div>
              <hr>
              <div class="card-body py-0">
                <div>
                  <% if cr.lectures.empty? %>
                    <h4>No lecture scheduled</h4>
                  <% else %>
                    <h4>Next Lecture</h4>
                    <h6><%= cr.lectures.first.start_time.strftime('%b %e, %l:%M %p') %></h6>
                    <h6>with: <%= cr.lectures.first.professional.company %></h6>
                  <% end %>
                </div>
              </div>
              <hr>
              <div class="card-body pt-1 pb-3">
                <a><%= link_to 'Schedule a lecture', professionals_path, :class=>"card-link btn btn-primary" %></a>
                <!-- <a href="#" class="card-link" data-toggle="modal" data-target="#myModal">Schedule a lecture</a> -->
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <!-- </div> -->
    </div>
    <!-- TAB 2 LECTURES -->
    <div id="lectures" class="tab-pane fade">
      <div class="container">
        <!-- LECTURE CARD -->
        <% @lectures.reverse_each do |l| %>
          <div class="card mb-3 p-5" style="width: 100%; border-radius: 12px; box-shadow: 0 0px 40px 0 rgba(0, 0, 0, 0.1);">
            <div class="row no-gutters">
              <div class="col-md-3">
                <div class="card-body">
                  <img src=<%= l.professional.user.profile_picture_url %> class="avatar-large card-img rounded-circle mt-3" alt="profile picture">
                </div>
              </div>
              <div class="col-md-9">
                <h3 class="card-body mt-3 pb-0">Topic: </i><%= l.name %></h3>
              <div class="card-body d-flex justify-content-between">
                <div>
                  <h4>with: <%= l.professional.user.first_name %> <%= l.professional.user.last_name %></h4>
                  <h6><i class="fas fa-building mr-3"></i><%= l.professional.company %></h6>
                  <h6><%= l.professional.title %></h6>
                  <div class="d-flex justify-content-between align-items-end">
                    <p class="card-text mt-3"><i class="fas fa-tag"></i>
                      <% l.professional.expertise_list.each do |e| %>
                        <small class="text-white px-2 py-2 mx-1" style="border-radius: 15px; background-color:#58C2F1;" ><%= e %></small>
                      <% end %>
                    </p>
                  </div>
                </div>
                <div class="mr-5">
                  <h4>Date</h4>
                  <h6><%= l.start_time.strftime('%A, %B %e') %></h6>
                  <h6><%= l.start_time.strftime('%l:%M %p') %> - <%= l.end_time.strftime('%l:%M %p') %></h6>
                  <% if l.confirmed? %>
                    <p class="btn btn-success p-1 mb-3">Confirmed</p>
                    <br>
                    <a><%= link_to 'View lecture', lecture_path(l), :class=>"btn btn-primary" %></a>
                  <% else %>
                    <p class="btn btn-warning p-1">Pending</p>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>





<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Create classroom</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@class_room.teacher, @class_room] do |f| %>
          <%= f.input :name %>
          <%= f.input :description %>
          <%= f.input :picture_url %>
          <%= f.label 'Interests' %>
          <%= f.input :interest_list, label: false %>
          <%= f.submit "Create Classroom", class: "btn btn-primary ml-2" %>
        <% end %>
      </div>
    </div>
  </div>
</div>