config/routes.rb
Rails.application.routes.draw do

  get 'signup_form/signup_form'

  devise_for :users

  resources :users, only: [:show]
  get '/professional_dashboard', to: 'users#professional_dashboard', as: 'p_dashboard'
  root to: 'pages#landing'
  get 'teacher_info', to: 'pages#teacher_info', as: :teacher_info
  get 'professional_info', to: 'pages#professional_info', as: :professional_info
  get '/tagged', to: "professionals#tagged", as: :tagged

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :professionals, except: :destroy do # only: [:index, :show, :new, :create, :edit, :update]
    resources :lectures, only: [:new, :create, :index] do
      resources :comments, only: [:new, :create]
    end
  end

  resources :teachers, only: [:new, :create, :edit, :update] do
    resources :lectures, only: [:index] do
      resources :comments, only: [:new, :create]
    end
    resources :class_rooms, only: [:new, :create]
  end

  resources :lectures, only: [:show, :edit, :update] do
    resources :comments, only: [:new, :create]
  end
  resources :videotokens, only: [:create]
end

app/views/pages/landing.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <% if current_user.professionals.empty? %>
          <li class="nav-item">
            <%= link_to "Profile", user_path(current_user), class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Profile", p_dashboard_path(current_user), class: "nav-link" %>
          </li>
        <% end %>
      <% end %>
      <div>
        <% if user_signed_in? %>
          <% if current_user.professionals.empty? %>
            <li class="nav-item">
              <%= link_to "Find Professionals", professionals_path, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Messages", "#", class: "nav-link" %>
            </li>
          <% end %>
        </div>
        <!-- ========= -->
        <!-- changed -->
        <li class="nav-item dropdown">
          <% if current_user.profile_picture_url != nil %>
            <%= image_tag current_user.profile_picture_url, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <!-- ======== -->
            <%= link_to "For teachers", teacher_info_path , class: "dropdown-item"%>
            <%= link_to "For professionals", professional_info_path , class: "dropdown-item"%>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<div class="banner-home">
  <div class="infobox">
    <h1 class="banner-h1" class="mb-3">Share your skills for a better good</h1>
    <p class="banner-p">We connect skilled professionals with schools and students in need</p>
    <!-- ====== -->
    <div class="d-flex justify-content-center mt-3 mb-3">
      <%= link_to "For Teachers", teacher_info_path, class: "btn btn-primary mr-2"%>
      <%= link_to "For Professionals", professional_info_path, class: "btn btn-white mr-2"%>
    </div>
    <!-- ======= -->
  </div>
</div>
<div class="container-main">
  <p class="container-main-p">Our platform connects skilled professionals with high schools to share their knowledge via video conferences.</p>
</div>
</div>
<div class="container-landing">
  <div class="d-md-flex flex-md-equal w-70">
    <div class="bg-white pb-4 m-4 pt-3 px-5 pt-md-5 px-md-5 text-center overflow-hidden w-50" style="border-radius: 21px; box-shadow: 0 9px 40px 0 rgba(0, 0, 0, 0.1);">
      <%= image_tag "teacher.png", alt: "teacher_img", :class => "image-landing" %>
      <div>
        <h2 class="display-5">For high school teachers</h2>
        <p class="lead mt-3">Enhance your classroom teaching</p>
      </div>
      <%= link_to "Learn more", teacher_info_path, class: "btn btn-primary mb-4"%>
    </div>
    <div class="bg-white pb-4 m-4 pt-3 px-5 pt-md-5 px-md-5 text-center overflow-hidden w-50" style="border-radius: 21px; box-shadow: 0 9px 40px 0 rgba(0, 0, 0, 0.1);">
      <%= image_tag "working-professional.png", alt: "working-professional.png", :class => "image-landing" %>
      <div>
        <h2 class="display-5">For working professionals</h2>
        <p class="lead mt-3">Share your work experience with students</p>
        <div>
          <%= link_to "Learn more", professional_info_path, class: "btn btn-primary mb-4"%>
        </div>
      </div>
    </div>
  </div>
  <div class="bg-white position-relative overflow-hidden mt-4 p-1 p-md-5 m-md-3 text-center bg-light" style="border-radius: 21px; box-shadow: 0 9px 40px 0 rgba(0, 0, 0, 0.1);">
    <div class="p-lg-5 mx-auto my-5">
      <p class="container-main-p">Help future generations make better career decisions</p>
    </div>
    <div class="product-device box-shadow d-none d-md-block"></div>
    <div class="product-device product-device-2 box-shadow d-none d-md-block"></div>
  </div>
</div>
<!-- ============== -->
<div class="banner-second">
  <div class="commerical-box">
    <ul class="commerical-list">
      <li class="commerical-icon">
        <i class="fas fa-desktop"></i>
        <p class="commerical-word">Instant online lectures</p>
      </li>
      <li class="commerical-icon">
        <i class="fas fa-globe-americas"></i>
        <p class="commerical-word">Networks all over the globe</p>
      </li>
      <li class="commerical-icon">
        <i class="far fa-comments"></i>
        <p class="commerical-word">Q&A sessions after the lecture</p>
      </li>
    </ul>
  </div>
</div>

<div class="card-product-page">
  <%= image_tag"teacher2.png", alt: "teacher"%>
  <div class="card-product-page-infos">
    <h2>Help your students seek better career options</h2>
    <p>Help students to connect with professionals to discover the world of work, such as industry requirements, opportunities, development paths and limitations.</p>
  </div>
</div>
<!-- ========================== -->
<div class="notification-teachers">
  <div class="testimonials">
    <%= image_tag "kelvin.png", alt: "Avatar", :class => "avatar-large landing"%>
  </div>
  <div class="testimonials-name">
    <h3><strong>Kelvin L.</strong></h3>
    <p><strong>Biology Teacher</strong></p>
    <p>Flower Bridge High School</p>
  </div>
  <div class="testimonials-content">
    <p>"Skill Transfer has been instrumental in getting my students to see the big picture of how the most minute details of what we learn in lecture are actually connected to how their professional careers will pan out 20, 30 even 40 years after they leave my classroom."</p>
  </div>
</div>
<!--  ============== -->
<div class="infobox-landing">
  <h2 class="center-landing">Our partner high schools</h2>
</div>
<!--  ============== -->
<div class="banner-second">
  <div class="imagbox">
    <ul class="inline-list-teacher">
      <li class= "img-schools">
        <%= image_tag "highschool1.png", alt: "Highschool_logo" %>
      </li>
      <li class= "img-schools">
        <%= image_tag "highschool5.png", alt: "Highschool_logo"%>
      </li>
      <li class= "img-schools">
        <%= image_tag "highschool6.png", alt: "Highschool_logo"%>
      </li>
      <li class= "img-schools">
        <%= image_tag "highschool7.png", alt: "Highschool_logo"%>
      </li>
      <li class= "img-schools">
        <%= image_tag "highschool8.png", alt: "Highschool_logo"%>
      </li>
    </ul>
  </div>
</div>
<!-- ========================== -->
<div class="card-product-page">
  <%= image_tag"professionals.png", alt: "professional"%>
  <div class="card-product-page-infos">
    <h2>Share your experiences, change others' lifes</h2>
    <p>Obtain personal satisfaction from making a difference to the career development of the others. Enhance your people skills such as leadership, interpersonal skills and communication.</p>
  </div>
</div>

<div class="notification-professionals">
  <div class="testimonials">
    <%= image_tag "jeff.png", alt: "Avatar", :class => "avatar-large landing"%>
  </div>
  <div class="testimonials-name">
    <h3><strong>Jeffery W.</strong></h3>
    <p><strong>Chief Technology Officer</strong></p>
    <p>Stark Industries</p>
  </div>
  <div class="testimonials-content">
    <p>"Best service ever! Helped me connect to the young talents in high school who have very strong potentials in their careers. I am also very glad to help them discover their future. JIA YOU everyone!"</p>
  </div>
</div>
<!--  ============== -->
<div class="infobox-landing">
  <h2 class="center-landing">Our partner companies</h2>
</div>
<!-- ============== -->
<div class="banner-third">
  <div class="imagbox">
    <ul class="inline-list-professional-second">
      <li class= "img-companies-big">
        <%= image_tag "omg.png", alt: "Company_logo" %>
      </li>
      <li class= "img-companies">
        <%= image_tag "pear.png", alt: "Company_logo"%>
      </li>
      <li class= "img-companies">
        <%= image_tag "enterprise.png", alt: "Company_logo"%>
      </li>
      <li class= "img-companies">
        <%= image_tag "unbrella.png", alt: "Company_logo"%>
      </li>
      <li class= "img-companies-medium">
        <%= image_tag "cyberdyne.png", alt: "Company_logo"%>
      </li>
      <li class= "img-companies-long">
        <%= image_tag "stark.png", alt: "Company_logo"%>
      </li>
    </ul>
  </div>
</div>
<!-- ============== -->
<div class="container-icon">
  <h2>Connect with us</h2>
  <ul class="icon-list">
    <li><a class="link-icon" href="#" target="_blank"><i class="fab fa-twitter-square"></i></a>
      <!--  <p>https://twitter.com/Skilltransfer1</p> -->
    </li>
    <li><a class="link-icon" href="#" target="_blank"><i class="fab fa-facebook"></i></a>
      <!-- <p>https://www.facebook.com/le.wagon.127</p> -->
    </li>
    <li><a class="link-icon" href="#" target="_blank"><i class="fab fa-linkedin"></i></a>
    </li>
    <li><a class="link-icon" href="#" target="_blank"><i class="fab fa-instagram"></i></a>
    </li>
    <li><a class="link-icon" href="#" target="_blank"><i class="fab fa-youtube-square"></i></i></a>
  </ul>
</div>
<!--  <div class="notification-professionals">
      <div class="testimonials">
      </div>
      <div class="testimonials-name">
        <h3><strong>Contact with us</strong></h3>
      </div>
    </div> -->
<!--  ============== -->
<div class="banner-white">
  <div class="card-product-landing-logo">
    <div class="card-product-landing-infos-logo landing-page-footer-main d-flex justify-content-start">
      <%= image_tag "skilltransfer.png", alt: "Skilltransfer_logo", :class => "logo3" %>
      <div class="footer-column d-flex flex-column">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">General</a>
        <%= link_to "Homepage", root_path , class: "nav-link"%>
        <% if user_signed_in? %>
          <%= link_to "My profile", user_path(current_user), class: "nav-link enable" %>
        <% else %>
          <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
        <% end %>
      </div>
      <div class="footer-column d-flex flex-column">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Browse more</a>
        <%= link_to "For professionals", professional_info_path , class: "nav-link"%>
        <!--  <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">For Teachers</a> -->
        <%= link_to "For teachers", teacher_info_path , class: "nav-link"%>
      </div>
    </div>
  </div>
</div>

app/views/pages/landingpage_teacher.html.erb
<div class="container">
  <h1>hello</h1>
  <div class="card-category p-5" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.glimpsecorp.com/wp-content/uploads/2018/04/iStock-821820418.jpg)">
  </div>
  <h1>Grant's Cocktail Collections</h1>
  <p><%= link_to "Customize Your Drink", new_cocktail_path, class: "btn btn-ghost" %></p>
  <div class="row">
    <% @cocktails.each do |cocktail| %>
      <div class="col-6 card p-4">
        <div class="card-image waves-effect waves-block waves-light">
          <img class="activator" src="https://cdn.liquor.com/wp-content/uploads/2011/01/diamond_blue-newest.jpg">
        </div>
        <p><%= link_to cocktail.name, cocktail_path(cocktail) %>
          <%= link_to cocktail_path(cocktail), method: :delete, data: {confirm: "Delete?"} do  %>
            <i class="far fa-eye-slash"></i>
          <% end %>
        </p>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/professional_info.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon navbar-default">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <% if current_user.professionals.empty? %>
          <li class="nav-item">
            <%= link_to "Profile", user_path(current_user), class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Profile", p_dashboard_path(current_user), class: "nav-link" %>
          </li>
        <% end %>
      <% end %>
      <!-- <li><%= link_to "For teachers", teacher_info_path , class: "nav-link"%>
      </li>
      <li><%= link_to "For professionals", professional_info_path , class: "nav-link"%>
      </li> -->
      <div>
        <% if user_signed_in? %>
          <% if current_user.professionals.empty? %>
            <li class="nav-item">
              <%= link_to "Find Professionals", professionals_path, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Messages", "#", class: "nav-link" %>
            </li>
          <% end %>
        </div>
        <!-- ========= -->
        <!-- changed -->
        <li class="nav-item dropdown">
          <% if current_user.profile_picture_url != nil %>
            <%= image_tag current_user.profile_picture_url, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <!-- ======== -->
            <%= link_to "For teachers", teacher_info_path , class: "dropdown-item"%>
            <%= link_to "For professionals", professional_info_path , class: "dropdown-item"%>
            <!-- ======== -->
            <!-- <div>
            <% if user_signed_in? %>
              <% if current_user.professionals.empty? %>
                <%= link_to "Find Professionals", professionals_path, class: "dropdown-item" %>
              <% end %>
            <% end %>
          </div> -->
            <!-- ======== -->
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<!-- <<<<<<< HEAD
<div class="banner-blue">
  <div class="infobox description">
    <div class="text-left">
      <h1 class="word-white">Share your knowledges and skills for a better good</h1>
      <a class="btn-flat-page" href="#">Sign up professional</a>
    </div>
  </div>
  ======= -->
<!-- new banner -->
<!-- ========================== -->
<div class="banner-pro" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1498758536662-35b82cd15e29?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=934&q=80)">
  <h2 class="mb-3">Share your knowledges and skills for a better good</h2>
</div>
<!-- ========================== -->
<div class="banner-gray">
  <div class="imagbox">
    <ul class="inline-list-professional">
      <li class= "img-companies-big">
        <%= image_tag "omg.png", alt: "Company_logo" %>
      </li>
      <li class= "img-companies">
        <%= image_tag "pear.png", alt: "Company_logo"%>
      </li>
      <li class= "img-companies">
        <%= image_tag "enterprise.png", alt: "Company_logo"%>
      </li>
      <li class= "img-companies">
        <%= image_tag "unbrella.png", alt: "Company_logo"%>
      </li>
      <li class= "img-companies-medium">
        <%= image_tag "cyberdyne.png", alt: "Company_logo"%>
      </li>
      <li class= "img-companies-long">
        <%= image_tag "stark.png", alt: "Company_logo"%>
      </li>
    </ul>
  </div>
</div>
<!-- ========================== -->
<div class="card-product-page">
  <%= image_tag"professionals.png", alt: "professional"%>
  <div class="card-product-page-infos">
    <h2>Share your experiences, change others' lifes</h2>
    <p>Obtain personal satisfaction from making a difference to the career development of the others. Enhance your people skills such as leadership, interpersonal skills and communication.</p>
  </div>
</div>
<!--  ============== -->
<div class="notification-professionals">
  <div class="testimonials">
    <%= image_tag "jeff.png", alt: "Avatar", :class => "avatar-large landing"%>
  </div>
  <div class="testimonials-name">
    <h3><strong>Jeffery W.</strong></h3>
    <p><strong>Secret Agent</strong></p>
    <p>Stark Industries</p>
  </div>
  <div class="testimonials-content">
    <p>"Best service ever! Helped me connect to the young talents in high school who have very strong potentials in their careers. I am also very glad to help them discover their future. JIA YOU everyone!"</p>
  </div>
</div>
<!-- ============== -->
<div class="banner-white">
  <div class="card-product-landing-logo">
    <div class="card-product-landing-infos-logo landing-page-footer d-flex justify-content-start">
      <%= image_tag "skilltransfer.png", alt: "Skilltransfer_logo", :class => "logo3" %>
      <div class="footer-column d-flex flex-column">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">General</a>
        <%= link_to "Homepage", root_path , class: "nav-link"%>
        <% if user_signed_in? %>
          <%= link_to "My profile", user_path(current_user), class: "nav-link enable" %>
        <% else %>
          <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
        <% end %>
      </div>
      <div class="footer-column d-flex flex-column">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Browse more</a>
        <%= link_to "For professionals", professional_info_path , class: "nav-link"%>
        <!--  <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">For Teachers</a> -->
        <%= link_to "For teachers", teacher_info_path , class: "nav-link"%>
      </div>
    </div>
  </div>
</div>

app/views/pages/teacher_info.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <% if current_user.professionals.empty? %>
          <li class="nav-item">
            <%= link_to "Profile", user_path(current_user), class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Profile", p_dashboard_path(current_user), class: "nav-link" %>
          </li>
        <% end %>
      <% end %>
      <!-- <li><%= link_to "For teachers", teacher_info_path , class: "nav-link"%>
      </li>
      <li><%= link_to "For professionals", professional_info_path , class: "nav-link"%>
      </li> -->
      <div>
        <% if user_signed_in? %>
          <% if current_user.professionals.empty? %>
            <li class="nav-item">
              <%= link_to "Find Professionals", professionals_path, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Messages", "#", class: "nav-link" %>
            </li>
          <% end %>
        </div>
        <!-- ========= -->
        <!-- changed -->
        <li class="nav-item dropdown">
          <% if current_user.profile_picture_url != nil %>
            <%= image_tag current_user.profile_picture_url, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <!-- ======== -->
            <%= link_to "For teachers", teacher_info_path , class: "dropdown-item"%>
            <%= link_to "For professionals", professional_info_path , class: "dropdown-item"%>
            <!-- ======== -->
            <!--  <div>
            <% if user_signed_in? %>
              <% if current_user.professionals.empty? %>
                <%= link_to "Find Professionals", professionals_path, class: "dropdown-item" %>
              <% end %>
            <% end %>
          </div> -->
            <!-- ======== -->
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<!-- ========================== -->
<div class="banner-pro" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://assets.pcmag.com/media/images/588342-classroom-teachers-student.jpg?thumb=y&width=810&height=456
)">
  <h2 class="mb-3">Help your students seek better career options</h2>
</div>
<!-- ========================== -->
<div class="banner-gray">
  <div class="imagbox">
    <ul class="inline-list-teacher">
      <li class= "img-schools">
        <%= image_tag "highschool1.png", alt: "Highschool_logo" %>
      </li>
      <li class= "img-schools">
        <%= image_tag "highschool5.png", alt: "Highschool_logo"%>
      </li>
      <li class= "img-schools">
        <%= image_tag "highschool6.png", alt: "Highschool_logo"%>
      </li>
      <li class= "img-schools">
        <%= image_tag "highschool7.png", alt: "Highschool_logo"%>
      </li>
      <li class= "img-schools">
        <%= image_tag "highschool8.png", alt: "Highschool_logo"%>
      </li>
    </ul>
  </div>
</div>
<!--  ============== -->
<div class="card-product-page">
  <%= image_tag"teacher2.png", alt: "teacher"%>
  <div class="card-product-page-infos">
    <h2>Help your students
      seek better career options</h2>
    <p>Help students to connect with professionals to discover the world of work, such as industry requirements, opportunities, development paths and limitations.</p>
  </div>
</div>
<!-- ========================== -->
<div class="notification-teachers">
  <div class="testimonials">
    <%= image_tag "kelvin.png", alt: "Avatar", :class => "avatar-large landing"%>
  </div>
  <div class="testimonials-name">
    <h3><strong>Kelvin L.</strong></h3>
    <p><strong>Biology Teacher</strong></p>
    <p>Flower Bridge High School</p>
  </div>
  <div class="testimonials-content">
    <p>"Skill Transfer has been instrumental in getting my students to see the big picture of how the most minute details of what we learn in lecture are actually connected to how their professional careers will pan out 20, 30 even 40 years after they leave my classroom."</p>
  </div>
</div>
<!--  ============== -->
<div class="banner-white">
  <div class="card-product-landing-logo">
    <div class="card-product-landing-infos-logo landing-page-footer d-flex justify-content-start">
      <%= image_tag "skilltransfer.png", alt: "Skilltransfer_logo", :class => "logo3" %>
      <div class="footer-column d-flex flex-column">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">General</a>
        <%= link_to "Homepage", root_path , class: "nav-link"%>
        <% if user_signed_in? %>
          <%= link_to "My profile", user_path(current_user), class: "nav-link enable" %>
        <% else %>
          <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
        <% end %>
      </div>
      <div class="footer-column d-flex flex-column">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Browse more</a>
        <%= link_to "For professionals", professional_info_path , class: "nav-link"%>
        <!--  <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">For Teachers</a> -->
        <%= link_to "For teachers", teacher_info_path , class: "nav-link"%>
      </div>
    </div>
  </div>
</div>